### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by amar3lo** [RPWimmer/zabbix-templates-arcserve-udp#1]
hi!

i got the following error when zabbix-server try to run this script:

The request was aborted: Could not create SSL/TLS secure
channel.
At C:\Zabbix\Arcserve_UDP_VMCount.ps1:39 char:10
+ $agent = New-WebServiceProxy -Uri $URI -Namespace WebServiceProxy -Cl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (https://bkp01...UDPService?ws
dl:Uri) [New-WebServiceProxy], WebException
+ FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.NewWe
bServiceProxy
The property 'CookieContainer' cannot be found on this object. Verify that the
property exists and can be set.
At C:\Zabbix\Arcserve_UDP_VMCount.ps1:44 char:1
+ $agent.CookieContainer = $cookieContainer

my arcserver run in https without a valid certificate...

**Comment by RPWimmer** [comment]
Hello,

the not valid certificate should not be a problem.
you can try the following:
I had an installation in which I had to use port 8014 while port 8015 was the right one for another installation.
Dont't know why by some UDP installation use 8014 and the other user 8015.

bye RPWimmer

**Comment by thvillegas** [comment]
> hi!
> 
> i got the following error when zabbix-server try to run this script:
> 
> The request was aborted: Could not create SSL/TLS secure
> channel.
> At C:\Zabbix\Arcserve_UDP_VMCount.ps1:39 char:10
> 
> * $agent = New-WebServiceProxy -Uri $URI -Namespace WebServiceProxy -Cl ...
> * 
> * CategoryInfo : ObjectNotFound: (https://bkp01...UDPService?ws
>   dl:Uri) [New-WebServiceProxy], WebException
> * FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.NewWe
>   bServiceProxy
>   The property 'CookieContainer' cannot be found on this object. Verify that the
>   property exists and can be set.
>   At C:\Zabbix\Arcserve_UDP_VMCount.ps1:44 char:1
> * $agent.CookieContainer = $cookieContainer
> 
> my arcserver run in https without a valid certificate...


Good Morning. I am experiencing the same problem. can you give me a way to this solution ???

**Comment by RPWimmer** [comment]
Check if you can open the URLs in Browser:
http://localhost:8015/services/UDPService?wsdl
or
https://localhost:8015/services/UDPService?wsdl

You should see the following:
![grafik](https://user-images.githubusercontent.com/23420219/115683599-e89c3b80-a356-11eb-8628-42a562b26e5b.png)

**Comment by thvillegas** [comment]
I managed to open it as yours as HTTP. With https this is giving big errors.  was that what has to open ??? and in the script you have to change something ???
![Backup](https://user-images.githubusercontent.com/9819099/115909411-e1059100-a441-11eb-8b50-d45d6f122442.JPG)

**Comment by RPWimmer** [comment]
Hi,
default the script is set to "http" and port "8015":
`# parameters for WDSL call. Set the HTTPS/HTTPS protocol and the used port`
`$protocol = "http" # https or https`
`$port = 8015 #port nummer`
Run the script with:
`.\Arcserve_UDP_VMCount.ps1 <username> <password> VMBackupFinishedCount <hostname or ip>`
Enable debug if you want to see more infos with:
`$Debug=$True`

bye RPWimmer

**Comment by RPWimmer** [comment]
Hi,
I haved changed the script and the template to a new version.
Now you can use:
.\Arcserve_UDP_VMCount.ps1 <domain> <username> <password> JobSuccessCount <hostname or ip>
br RPWimmer
