### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oguzhansrky** [RPWimmer/zabbix-templates-arcserve-udp#2]
Hi, 

Are you sure this is working? You can write some more humane documents.

![image](https://user-images.githubusercontent.com/52497227/102921962-5403f880-449e-11eb-81f6-e4fbca7048bd.png)

Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "New-WebServiceProxy : The request was aborted: Could not create SSL/TLS secure
channel.
At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:39
char:10
+ $agent = New-WebServiceProxy -Uri $URI -Namespace WebServiceProxy -Cl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (https://localho...UDPService?ws
dl:Uri) [New-WebServiceProxy], WebException
+ FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.NewWe
bServiceProxy
The property 'CookieContainer' cannot be found on this object. Verify that the
property exists and can be set.
At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:44
char:1
+ $agent.CookieContainer = $cookieContainer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyNotFound

get-member : You must specify an object for the Get-Member cmdlet.
At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:47
char:23
+ $agentinfo = $agent | get-member -type method
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : CloseError: (:) [Get-Member], InvalidOperationEx
ception
+ FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Command
s.GetMemberCommand

You cannot call a method on a null-valued expression.
At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:51
char:1
+ $res = $agent.login($user, $pass, $dom)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:62
char:1
+ $jobHistory = $agent.getJobHi

**Comment by thvillegas** [comment]
> Hi,
> 
> Are you sure this is working? You can write some more humane documents.
> 
> ![image](https://user-images.githubusercontent.com/52497227/102921962-5403f880-449e-11eb-81f6-e4fbca7048bd.png)
> 
> Value of type "string" is not suitable for value type "Numeric (unsigned)". Value "New-WebServiceProxy : The request was aborted: Could not create SSL/TLS secure
> channel.
> At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:39
> char:10
> 
> * $agent = New-WebServiceProxy -Uri $URI -Namespace WebServiceProxy -Cl ...
> * 
> * CategoryInfo : ObjectNotFound: (https://localho...UDPService?ws
>   dl:Uri) [New-WebServiceProxy], WebException
> * FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.NewWe
>   bServiceProxy
>   The property 'CookieContainer' cannot be found on this object. Verify that the
>   property exists and can be set.
>   At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:44
>   char:1
> * $agent.CookieContainer = $cookieContainer
> * 
> * CategoryInfo : InvalidOperation: (:) [], RuntimeException
> * FullyQualifiedErrorId : PropertyNotFound
> 
> get-member : You must specify an object for the Get-Member cmdlet.
> At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:47
> char:23
> 
> * $agentinfo = $agent | get-member -type method
> * 
> * CategoryInfo : CloseError: (:) [Get-Member], InvalidOperationEx
>   ception
> * FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Command
>   s.GetMemberCommand
> 
> You cannot call a method on a null-valued expression.
> At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:51
> char:1
> 
> * $res = $agent.login($user, $pass, $dom)
> * 
> * CategoryInfo : InvalidOperation: (:) [], RuntimeException
> * FullyQualifiedErrorId : InvokeMethodOnNull
> 
> You cannot call a method on a null-valued expression.
> At C:\Zabbix\zabbix_agentd.conf.d\scripts\arcserve\Arcserve_UDP_VMCount.ps1:62
> char:1
> 
> * $jobHistory = $agent.getJobHi

Good Morning. I am experiencing the same problem. can you give me a way to this solution ???

Thank you very much in advance

**Comment by RPWimmer** [comment]
Check if you can open the URLs in Browser:
http://localhost:8015/services/UDPService?wsdl
or
https://localhost:8015/services/UDPService?wsdl

You should see the following:
![grafik](https://user-images.githubusercontent.com/23420219/115682098-6cedbf00-a355-11eb-8476-b073ca266293.png)

**Comment by RPWimmer** [comment]
Closed the ticket
