### ISSUE TITLE
Value "Exception calling "login" with "3" argument(s): "Invalid user credentials !"

### ISSUE THREAD

**Issue by everaldoscabral** [RPWimmer/zabbix-templates-arcserve-udp#3]
![image](https://user-images.githubusercontent.com/53796085/115879898-8871cc00-a420-11eb-8d9a-4b9aaf5c1084.png)

Hey! 

I use to login "domain \ user" and is giving this error.

URL /services/UDPService?wsdl opens normally.

**Comment by RPWimmer** [comment]
Hi,
set the following in der script:
`$Debug=$True`
and let the script run again. 
Look at the output from debug. Are the $user, $pass and $dom values filled.

**Comment by everaldoscabral** [comment]
> Hi,
> set the following in der script:
> `$Debug=$True`
> and let the script run again.
> Look at the output from debug. Are the $user, $pass and $dom values filled.

Hi! = )

Yes, values filled.

I used the link below, lines 144 - 177 to solve but it is still not good.

https://github.com/N-able/CustomMonitoring/blob/master/Arcserve%20UDP/Arcserve_UDP_job_polling.ps1

**Comment by RPWimmer** [comment]
Hi,
can you see data from the arcserve job in the debug log?
If not, try to change the "$RecentJobID" to a higher value (example):
`# You must try to set the right JobID for the VM job (try it first with 1): `
`$RecentJobID = 2`

br RPWimmer

**Comment by everaldoscabral** [comment]
> `# You must try to set the right JobID for the VM job (try it first with 1): `

Same thing. = /

**Comment by RPWimmer** [comment]
Hi,
how many arcserve jobs are created on this arcserve UDP installation?
Look at the jobs to find the correct JobID for the VM Backup job.
I use not the "Arcserve_UDP_job_polling.ps1" script, because it responds too slowly for then zabbix agent (Tiemout 30 sec).
But if you found a solution you can use it and change the template items.
br RPWimmer

**Comment by everaldoscabral** [comment]
> Hi,
> how many arcserve jobs are created on this arcserve UDP installation?
> Look at the jobs to find the correct JobID for the VM Backup job.
> I use not the "Arcserve_UDP_job_polling.ps1" script, because it responds too slowly for then zabbix agent (Tiemout 30 sec).
> But if you found a solution you can use it and change the template items.
> br RPWimmer

The problem is in the login with the webservice, I use the domain.

**Comment by everaldoscabral** [comment]
![image](https://user-images.githubusercontent.com/53796085/116099961-dbe35480-a682-11eb-869f-70667753cafc.png)
![image](https://user-images.githubusercontent.com/53796085/116100053-f4ec0580-a682-11eb-9e72-9987f666bf89.png)

**Comment by RPWimmer** [comment]
Hi,
the variable $domain (or in my script $dom) stands for the hostname or the ip-address of the arcserve host.
I used the loginname without the domain part (DOMAIN\). Please try this.
br RPWimmer

**Comment by everaldoscabral** [comment]
> Hi,
> the variable $domain (or in my script $dom) stands for the hostname or the ip-address of the arcserve host.
> I used the loginname without the domain part (DOMAIN). Please try this.
> br RPWimmer

Your script:

$dom ==> hostname

![image](https://user-images.githubusercontent.com/53796085/116105578-d3d9e380-a687-11eb-8dca-fa19a9ed47c3.png)

If using domain\user generates an error with $user variable.

Variable $domain ==> Domain of the machine.

**Comment by RPWimmer** [comment]
Hi,
I haved changed the script and the template to a new version.
Now you can use:
`.\Arcserve_UDP_VMCount.ps1 <domain> <username> <password> JobSuccessCount <hostname or ip>`
br RPWimmer

**Comment by thvillegas** [comment]
Good morning, where am I missing ??? can you help me?


PS C:\Program Files\Zabbix Agent> .\Arcserve_UDP_VMCount.ps1 rh mococa XXXXXXX JobSuccessCount 10.12.2.90
Exception calling "getJobHistoryList" with "3" argument(s): ""
At C:\Program Files\Zabbix Agent\Arcserve_UDP_VMCount.ps1:90 char:1
+ $jobHistory = $agent.getJobHistoryList($RecentJobID, $null, $null)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SoapException
 
0

**Comment by RPWimmer** [comment]
Try; $RecentJobID = 1

**Comment by fellipedemoraes** [comment]
> Good morning, where am I missing ??? can you help me?
> 
> PS C:\Program Files\Zabbix Agent> .\Arcserve_UDP_VMCount.ps1 rh mococa XXXXXXX JobSuccessCount 10.12.2.90
> Exception calling "getJobHistoryList" with "3" argument(s): ""
> At C:\Program Files\Zabbix Agent\Arcserve_UDP_VMCount.ps1:90 char:1
> 
> * $jobHistory = $agent.getJobHistoryList($RecentJobID, $null, $null)
> * ```
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : SoapException
>   ```
> 
> 0

UP
